<?php

// A command line script to generate the file verses.inc.php

if (php_sapi_name()!='cli') {
    echo "<h1>Dette script kan kun eksekveres fra kommandolinjen</h1>";
    die();
}


require_once('oversigt.inc.php');


function look_through(string $book, int $chapt)
{
    global $outfile, $filetype;
    
    switch (is_array($filetype[$book]) ? $filetype[$book][$chapter] : $filetype[$book]) {
        case 'sfm':
            echo "$book er i SFM-format, som ikke understøttes af buildverses.php\n";
            break;

        case 'txt':
            $txt = file_get_contents(sprintf('tekst/%s%03d.txt',$book,$chapt));

            $verses = [];
            for ($verse = 1; $verse < 177; ++$verse)
                if (strstr($txt, sprintf("v%d ",$verse))!==false)
                    $verses[] = $verse;
                
            fwrite($outfile, "\$verses['$book'][$chapt] = [" . implode(',',$verses) . "];\n");
            break;
    }
}

$outfile = fopen("verses.inc.php","w");
fwrite($outfile, "<?php\n\n// DO NOT EDIT. This file is generated by buildverses.php\n\n");

foreach ($style as $book => $val) {
    if (is_array($val)) {
        foreach ($val as $chapt => $mature) {
            if (in_array($chapt,$chap[$book]) && $mature == $modenhed['ufuldstændigt'])
                look_through($book,$chapt);
        }
    }
    elseif ($val == $modenhed['ufuldstændigt']) {
        // Hele bogen gennemsøges
        foreach ($chap[$book] as $chapt) 
                look_through($book,$chapt);
    }
}
            
    
