php replaceitsfm.php -n EXO generated/EXO.sfm ../tekst/2mos*.txt
#php replaceitsfm.php -n NUM generated/NUM.sfm ../tekst/4mos*.txt
#php replaceitsfm.php -n JDG generated/JDG.sfm ../tekst/dom*.txt
#php replaceitsfm.php -n RUT generated/RUT.sfm ../tekst/ruth*.txt
#php replaceitsfm.php -n JOB generated/JOB.sfm ../tekst/job*.txt
#php replaceitsfm.php -n PSA generated/PSA.sfm ../tekst/sl*.txt
#php replaceitsfm.php -n ISA generated/ISA.sfm ../tekst/es*.txt
#php replaceitsfm.php -n OBA generated/OBA.sfm ../tekst/obad001.txt
#php replaceitsfm.php -n JON generated/JON.sfm ../tekst/jon*.txt
#php replaceitsfm.php -n NAM generated/NAM.sfm ../tekst/nah*.txt
#php replaceitsfm.php -n HAB generated/HAB.sfm ../tekst/hab*.txt
#php replaceitsfm.php -n ZEP generated/ZEP.sfm ../tekst/sef*.txt
#php replaceitsfm.php -n HAG generated/HAG.sfm ../tekst/hagg*.txt
#php replaceitsfm.php -n ZEC generated/ZEC.sfm ../tekst/zak*.txt
